---
    - name: restart_nginx
      service: 
        name: nginx
        state: restarted

    - name: reload_nginx
      service: 
        name: nginx
        state: reloaded

    - name: restart_sshd
      service: 
        name: sshd
        state: restarted
        enabled: yes
