---
    - name: Add 'AllowUsers' to sshd_config
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        line: 'AllowUsers {{ webuser_name }}'
        state: present

      notify:
        - restart_sshd
